---
abstract: unknown
author:
  - 'Eric Waters  <ewaters gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-Graphics-ColorDistance
no_index:
  directory:
    - t
    - inc
requires:
  PDL: v2.4.4
  PDL::Core::Dev: 0
  Test::More: 0
version: v0.0.1
